sizes = [
    "tall ",
    "short ",
    "stubby ",
    "giant ",
    "tiny ",
    "shrunken ",
    ""
]

colors = [
    "red ",
    "blue ",
    "yellow ",
    "green ",
    "purple ",
    "black ",
    "white ",
    "lilac ",
    "orange ",
    "maroon ",
    "beige ",
    "butter ",
    "sage ",
    "lime ",
    "azure ",
    "indigo ",
    "lavender ",
    "violet ",
    "pink ",
    "salmon ",
    "rouge ",
    "brown ",
    "silver ",
    "gold ",
    "bronze ",
    "bright ",
    "light ",
    "murky ",
    "dark ",
    "muted ",
    "luminecent ",
    "shiny ",
    "opalencent ",
    ""
]

patterns = [
    "speckled ",
    "marbled ",
    "striped ",
    "spotted ",
    "blotched ",
    "banded ",
    "painted ",
    ""
]

special_adjs = [
    "winged ",
    "tipped ",
    "spiked ",
    "horned ",
    "symmetrical ",
    "asymmetrical ",
    "mountain ",
    "arctic ",
    "desert ",
    "leathery ",
    "soft ",
    "water ",
    "amorphous ",
    "tentacled ",
    "dancing ",
    "swaying ",
    "howling ",
    "lureing ",
    "seasonal ",
    "poisonous ",
    "venomous ",
    "carnivorous ",
    "domed ",
    "spiral ",
    "tipped ",
    "spicy ",
    "tree ",
    "wood ",
    "dwarf ",
    ""
]

nouns = [
    "flower",
    "flower-petal",
    "flower-stem",
    "snail",
    "snail-mucus",
    "lizard",
    "lizard-venom",
    "beetle",
    "beetle-gland",
    "hopper",
    "leaf",
    "herb",
    "herb-root",
    "root",
    "fish",
    "fish-roe",
    "fish-gland",
    "frog",
    "frog-mucus",
    "snake-venom",
    "snake",
    "tree-bark",
    "clam",
    "coral",
    "crab",
    "moth",
    "mushroom",
    "alge",
    "mold",
    "moss"
]